apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
type: Opaque
data:
    password: ENC[AES256_GCM,data:6MzKTfYXNzHW45rU,iv:wkUOskSgIh7eIxnSsuQ3C6D4JQCVgC56bZKCwCSDIhY=,tag:pCO8nEQUHQ6BmNIg36e47w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16xjg2w29gttuq0708sejnum4pg9yttdetcj4ad8cysaku85hcs5spje6m6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlR2xrS2VVajl2VmFlRzQ5
            YkVjekl0OUhwVUhGNzU3Vk1HRHp5bThBVVM4Cm8rRDZvSWRwbW8yQnRjNGdNV29r
            TWl4Rmprc2ZjZlo4VHRvd0RxakxLcHcKLS0tIENScTd2OTI4VVh5MkN5NkxBRkg4
            TExWbkh1QTBGTzB3Yk1OMDYwbE5qYUUK1aWMN31J7EKJy475IHzgwREh/BV0Rcon
            aOzPTExfXwcwBL9g+Y5dYGfj2m1fanIKXvggmsK8Y8kBBwPdDDwAWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T03:37:03Z"
    mac: ENC[AES256_GCM,data:etkIV3qU4IpxHn7sZBIjYKdiiz+glnLGgvAz3ORrdp3Dx0IwReOuFwUmxxe9g6J56tAJx3klXL7dOiAN4hkzSio6ocxHbiV4lPtvvS2cVQG8t3emS0+ifLVN4ZDqCRtN817pKmHUdYUG4NqFo2nNiOCeU1V8jei57QiZuUqkUlU=,iv:gb2pTdVcTmd7opiV+yj3AY3ZUduZhD56uBdsL2S2wrk=,tag:GrBp/hH09GltV7wFQs09cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
