apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - namespace.yaml
  - configs
  - kube-prometheus-stack
  - ../../../../helm/grafana/helm-repository.yaml
  - loki-stack
  - ../../../../helm/prometheus-community/helm-repository.yaml

configMapGenerator:
  - name: flux-grafana-dashboards
    files:
      - configs/dashboards/control-plane.json
      - configs/dashboards/cluster.json
      - configs/dashboards/logs.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring

  - name: flux-kube-state-metrics-config
    files:
      - kube-prometheus-stack/kube-state-metrics-config.yaml
    # options:
    #   labels:
    #     app.kubernetes.io/part-of: flux
    #     app.kubernetes.io/component: monitoring

configurations:
  - kube-prometheus-stack/kustomizeconfig.yaml
