apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
type: Opaque
data:
  age.agekey: IyBwdWJsaWMga2V5OiBhZ2UxNnhqZzJ3MjlndHR1cTA3MDhzZWpudW00cGc5eXR0ZGV0Y2o0YWQ4Y3lzYWt1ODVoY3M1c3BqZTZtNgpBR0UtU0VDUkVULUtFWS0xVEo4R1NEUjBLTEZGV1RYSkhUTFJRUzdSUFZUN0RIRVJFSFc3VFE5S1hFV0VDTDc2SkQ3UzRZV0pRMw==