apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
type: Opaque
data:
    admin-user: ENC[AES256_GCM,data:D/4V5g1nM4k=,iv:dQDyNlUjux521psxbj4q8wHhBAP8lfxfnxstuKRDBYQ=,tag:Kae0+LrhiSNJrbdZLnHBKA==,type:str]
    admin-password: ENC[AES256_GCM,data:vS0BFvgj805kjZBU,iv:vUCSGZmCH4CYmWejZiSBez7biCe6dfxf4oMshEVI8UM=,tag:/bCt+BuZwB5I5z7u75ki9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qqlzpgsdzxfsynkcamac9cpwup5x08t537pk6gzlvq38j592frs78y0nz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteW8rSHpNK2hvN3FYbkFJ
            OVg1bHA5SkovMGZnbHZqUDRXa0M2cXlEbDBNCjdIK0p2ZXZxcVdGZzNGZUM4bkZP
            TkVNUG1WL08wTjYzcC9paERoU3UwRW8KLS0tIFM0SnAwdjFzWGhiRTBCUDBYZFJI
            cW1keWY4VitjQUtOSUlJUW1tWkNlN2sKChTIJi7SgP8l5lWrwR0VqPornQPxt+da
            rB9+GgPRANv1DSo5OFJ/U/E0jTxrdKoZdLz1IA8XqVGIxAl8Fx8ahA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-20T15:31:05Z"
    mac: ENC[AES256_GCM,data:uB5/WC4LhH0i3AXybNYg8sp9srHAvNa/G1AUcwGYN93kZROSOtugSGXar3EYuTeYPLJUF6Ebttpq2JLQq5D7URHTNpVEKqDfYqR3s/rYTsKVe07LbPXu0eIA3DbDMGbIXSSaENcaV2bFGN04SFU0cZVg/ylErNq3/cn2CRHvz38=,iv:e5QZSAb2AnrAkvOxzUCmJShyJws5uln33o/JEjXfB5k=,tag:CjFT4PD/pkgQ94Ih0A0dvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
