apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: fundhub-api-dev
  namespace: flux-system
spec:
  image: titan29/fundhub-api-dev
  interval: 1m
  secretRef:
    name: regcred
