apiVersion: apps/v1
kind: Deployment
metadata:
  name: fundhub-client-dev
spec:
  selector:
    matchLabels:
      app: fundhub-client-dev
  template:
    metadata:
      labels:
        app: fundhub-client-dev
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: fundhub-client-dev
          image: titan29/fundhub-client-dev:12 # {"$imagepolicy": "flux-system:fundhub-client-dev"}
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "10m"
          ports:
            - containerPort: 3010
          env:
            - name: BASE_URL
              value: http://fundhub-api-dev-svc.backend.svc.cluster.local
            - name: PORT
              value: "3010"
            - name: TEST_DEBUG
              value: OK
