apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: fundhub-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: fundhub-api
  policy:
    numerical:
      order: asc
