apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 2m
  timeout: 10m
  prune: true
  path: ./main/staging/namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age # sama secret yang ada di namespace `flux-system` telah di buat