apiVersion: v1
kind: Secret
metadata:
    name: fundhub-api-dev-secret
type: Opaque
data:
    DB_HOST: ENC[AES256_GCM,data:Dg+GdYAgP2MsQcHHM4V4dIXD97U=,iv:4HYvcFWUJ+PbPisMqVjJ4qdTnTx2b0SFSxXgdsQzXs8=,tag:ehl49LrXF6/TJ/euHnEytQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:83Y46b0Emhk=,iv:nGCdUAhrxE7Buyu9T1suPisHEamP+fUHVTeBeF44NHQ=,tag:MPx9xi9vEFx99mZWM2L8cQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:6Q2bHJrX1rtO0EFA,iv:MDl6aYCv7DpiYXQevXte1+/tB86xGf0bkvFUjzGR4qI=,tag:fibl4qCdn/3QymaqgoOhsw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:Q/ayGauKsLueKBqnN6cwMD3Ki7U=,iv:Q8mDlXZAOPdCuYUuiN2jR3ZTHkj4Yf+hAuMmvt0YJVQ=,tag:/00R7KN2SNJs8B0ttv6bsw==,type:str]
    DB_PORT: ENC[AES256_GCM,data:2fWaJ2R+Ngs=,iv:Jt4OUU9P+gfsNtZHD0D3h/b2IvK8naONZviuhJTcC1I=,tag:bBpUenzJlDVQhKmKvoNYyg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:vAnA5K+YNy3EZhT/XStCD6LcXWb0dywy1z6jQlicYjxz3MEdM66eJH/l4L8GrXxOR1Xo0tPKSIE6S9gzIXcCU8CR1Yyqdhi6O33vtLU7oujJVywBkwmud9xFUWAgU7Un9FM40z+PPTjLk0QKu/WpFTtfXPJ4aS6/QIp+Rkgs1p4=,iv:FLMSmdOnhl12s41xWAYu/KBym0RIz5JdUc/hwlreBEU=,tag:kYdqOcl/ZMwmHFz97gxu8w==,type:str]
    SERVER_KEY: ENC[AES256_GCM,data:AQzuNKg6ZgXPX/JtL1SnLagqTNrZzBdR8MNknIEsXjIYpJfMjVVq4nN4fI8+Ph7Qp5pmJQ==,iv:b0bbhdc8/YoPzJlcWCXZc4yqNGr/UxXJmPiVzn9Khcc=,tag:1ezY52N/V71qL58MUgIgvA==,type:str]
    CLIENT_KEY: ENC[AES256_GCM,data:R0QcPG8jb/tyxg2RglxtUDZiIUCaqR7hDVumLNxIU8LR/TP0K+DJhA==,iv:5Sxi9MeUEhJorT73/SkrAtnDlkK+dZQMqx39w6U+Fts=,tag:94XigQI7Ja0DftGgOy89dA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:BqPKH54rS1Q=,iv:b+UQvyeLCzIs4dI9s/akz87lPSgLcRsyTkZZaPAuxmk=,tag:eBX5wDIOSEMKN68x87niGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qqlzpgsdzxfsynkcamac9cpwup5x08t537pk6gzlvq38j592frs78y0nz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWUFLYnNPam91SzdWY1Zt
            azlvQjM3SHVWRDZ6L0ZaVklSNlBJcXFUMW1RCmIvZ0p5Q29BMERwL1lTYTkxQSts
            cnpRZTljdEtVamNuTE5FdzJrUWF4WGcKLS0tIE5CbnVFM0ZYYnNvRHFrWHFNRzdB
            RmZtYlVIa3E3K3J1QnNxRWpMbzZFd2sKwZkSfUIb6mrcvYt7WleYG1C/3lESoqZi
            CacQeq9LQv7XfGjiUuEIPbct0V2DmnzNw5nOwMj8fqbf7Z16x0zpug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-20T04:51:07Z"
    mac: ENC[AES256_GCM,data:W5N21l4KLbjYKYCJ29OuItSlfz34mY7ycY4n5Sb82Exn6AenSFHkDUZhbyWyeUlW72Z6kJqVWhU13ns8Qv2mperFdsdIxJ1KlwOcuFk++lF1+0yti8l5yZ1KBMrzHbCHYNh4n5JImrNFzttXZhFKZ91QcuAJdV4wdlqXDhyHAmk=,iv:SOVYuT3jBUNv7QtZsD3HP/axPUG0BHDmDabL++2Z4QM=,tag:RIsdldxv2edjb9esfDKHTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
