apiVersion: v1
kind: Secret
metadata:
    name: fundhub-api-secret
type: Opaque
data:
    DB_HOST: ENC[AES256_GCM,data:t2GDisKeM32auK4Qp6BblqzSdTA=,iv:bjOuW0z7KauEMaIQ5x9Tr+HxsDlKaZG9/5HkazzOaTs=,tag:TVsg75KktYX8/m5/agpQXw==,type:str]
    DB_USER: ENC[AES256_GCM,data:ugRfP2f8XdU=,iv:OIodeROVpw1wga7ee+o1mwVe4XC6I8XSCko1s1Bd2EU=,tag:xMSzMyqbLS8Qyu6E4AsNYA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:jljszMZBWBIKVigA,iv:Td5A+PUHD7DzYnssDvejkLwqstqvhARskYnvrc0dZnQ=,tag:6rIqcdbvYTzEAqgoa5MMjg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:ja3Jo1vasZnX7qgf,iv:osGFXNyp3QL7K1YC3SCAS5B5GXMgGdU/9LLYj9lzAV4=,tag:1Rl/L362Gd1n3ZCG5KJh0g==,type:str]
    DB_PORT: ENC[AES256_GCM,data:0tk+zrmI/nA=,iv:94aCk53+DAFH3mMLhWd/mhkUzoyaJnUZL2MqYQb/33M=,tag:rCYhBfeLnhcJURHY33ldiQ==,type:str]
    SERVER_KEY: ENC[AES256_GCM,data:SKT8sYgh8gLdd1mcL761yogGhCjcRbDCTKfJaUuxCqdkSuF+emju6yqdXVgf2qoS,iv:1/CSZjDCeWS6l183vR0XGIYI59wyUYYUa1G8iUMqbgM=,tag:ICyDYPge07fTSBB3V7/uwA==,type:str]
    CLIENT_KEY: ENC[AES256_GCM,data:lih6FY3AZl6AtmgLSSpmEaNtWshYSvgM1OGE4dYHFvBUzKB+,iv:JLBcbw5GUZGCvUM3RVC0XwU+0l/YrafI274U/BvjlvY=,tag:QeSf5LdJTzAfOzV+1G+8lA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:2Opbr/FEyNI=,iv:spFaWA4FQFcChjMUcme8gzFux4IVFW2Ob1qJuPcRw+I=,tag:zzzoPqAnqmGFfjOThDnQOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16xjg2w29gttuq0708sejnum4pg9yttdetcj4ad8cysaku85hcs5spje6m6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSkpublRzNzFLYUpCT3BT
            QkVGcWVpOXl2S2x2SnE0cTVwQ0JTL1NSeUUwCmt2QmJJYWtxbTJsNDFxaEhNM3No
            UzdXM0ZRRHZCT0o2UGRwOVVSbmZNcVEKLS0tIEFGdDFaY0h2bGZVbEhlQlVOTEw5
            UzhVMjVEYW4vMDBzT0FqVE9EZU12T1UKUu6OtWFpuzZtuQlT0fKZWKHvhUQXjQcb
            p9TfP4kENbqfGdvqZzMQntt7wVtJCSucqygbOqoiT2FCmp6wjpBRtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-20T06:47:00Z"
    mac: ENC[AES256_GCM,data:RJgX5P6EDsJuZU2SkwOPdGcTDBxXWrYHbjvbQqLaFghi3vahmjM36iSFHyw1nrMJMLW6rBTnLEdMZQ7a8idUeQlBbHee2HQedF9I/MvGmjla5InXzNQmYEWl7byW+YxHRnvd71IRUJJhR0OK2MDdIXjxnxnhPtFQngyEb8UyAD8=,iv:/MwunL260Y51ALIlUmhywyP5iYVyftgDjhagL0a01Ok=,tag:eNwqqBnR3bXGCqS5y5hDmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
