apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 1m
  values:
    admin:
      existingSecret: grafana-admin-secret
      userKey: admin-user
      passwordKey: admin-password