apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: grafana
spec:
  providerRef:
    name: grafana
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: flux-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: grafana
spec:
  type: grafana
  address: "http://grafana.monitoring.local/api/annotations"
  secretRef:
    name: grafana-token